services:
  back-minitrello:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: back-miniTrello
    ports:
      - '4002:5000'
    env_file:
      - .env
    networks:
      - miniTrello-networks
        
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      -  miniTrello-networks
networks:
  miniTrello-networks:
    external: true
